apiVersion: v1
kind: Service
metadata:
  name: temporal-codec-server-service
  labels:
    app: temporal-codec-server
spec:
  ports:
  - port: 3000
    name: server
  type: ClusterIP
  selector:
    app: temporal-codec-server